### ISSUE TITLE
certain pages don't render on website

### ISSUE THREAD

**Issue by dlemire60** [CybersecurityAutomationWorkshop/caw2022#18]
Certain pages linked from the website home page display their raw markdown content when clicked, rather than being rendered in the website theme. The two I'm sure have this issue are CODE_OF_CONDUCT.md and CONTRIBUTING.md. Note this only happens when viewing the website generated by GitHub Pages; if you're directly in GitHub they will render like any other markdown page.

I suspect the issue is the ALL_CAPS filenames, but I'm not 100% sure of that.

**Comment by sparrell** [comment]
fixed
