### ISSUE TITLE
return to home not consistently available

### ISSUE THREAD

**Issue by dlemire60** [CybersecurityAutomationWorkshop/caw2022#6]
I guess this is a shortcoming of the selected template for the website, but there isn't any consistently placed / available link on the subordinate pages to jump back to the website home page. 

The [Previous Workshops page](http://www.cybersecurityautomationworkshop.org/PrevResults/) includes a "Return to Home" link in its content. However, since the link is under a heading that also reads Return to Home, you get a Return to Home item in the TOC list at left that's non-functional, which is somewhat confusing.

**Comment by sparrell** [comment]
Each page has a (or at least should have a) return to home "section" that includes a title ("return to home") and a link that actually returns you to home. The Table of Contents lists the section headers. So you click on 'return to home' in the sidebar and it brings you to the section "return to home" where you have to click on the actual link to get returned to home. Suggestions welcome on how to do it differently.

**Comment by dlemire60** [comment]
OK, I see that. It's a bit unconventional, but unless the theme offers some way to add a home page link to the header so something appears there consistently, there's probably not much else that can be done.
